---
- name: Set PostgreSQL environment variables.
  template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    mode: 0644
  notify: restart postgresql

- name: Ensure PostgreSQL data directory exists.
  file:
    path: "{{ postgresql_data_dir }}/{{ postgresql_cluster_name }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/{{ postgresql_cluster_name }}/PG_VERSION"
  register: pgdata_dir_version

- name: Ensure PostgreSQL database is initialized.
  command: "pg_createcluster -d {{ postgresql_data_dir }}/{{ postgresql_cluster_name }} \
            {{ postgresql_version }} {{ postgresql_cluster_name }}"
  become: true
  become_user: "{{ postgresql_user }}"
  when:
    - not pgdata_dir_version.stat.exists
    - ansible_os_family == 'Debian'

- name: Configure non standard PostgreSQL port.
  lineinfile:
    dest: "{{ postgresql_config_path }}/{{ postgresql_cluster_name }}/postgresql.conf"
    regexp: "^#?port.+$"
    line: "port = {{ postgresql_port }}"
    state: present
  notify: restart postgresql
  when:
    - postgresql_port != 5432
    - ansible_os_family == 'Debian'

- name: Ensure PostgreSQL database is initialized.
  command: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}/{{ postgresql_cluster_name }}"
  become: true
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
  when:
    - not pgdata_dir_version.stat.exists
    - ansible_os_family == 'RedHat'
