---
# Variable configuration.
- include_tasks: variables.yml

# Install official repository
- name: Install PGDG repository.
  include_tasks: pgdg-{{ ansible_os_family }}.yml
  when:
    - ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
    - postgresql_pgdg is defined
    - postgresql_pgdg

# Setup/install tasks.
- name: OS setup/install tasks.
  include_tasks: setup-{{ ansible_os_family }}.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

- include_tasks: initialize.yml
- include_tasks: configure.yml

- name: restart postgresql
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_restarted_state }}"
    sleep: 5

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml
