---
# tasks file for gitops-add-db
- name: Create DB
  become: true
  become_user: postgres
  postgresql_db:
    name: miketest
    encoding: UTF-8
    lc_collate: en_NZ.UTF-8
    lc_ctype: en_NZ.UTF-8
    state: present
    template: template0
